services:
  account-db:
    image: postgres:18
    container_name: account-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: AccountService
    ports:
      - "5433:5432"
    volumes:
      - account_db_data:/var/lib/postgresql

  transaction-db:
    image: postgres:18
    container_name: transaction-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: TransactionService
    ports:
      - "5434:5432"
    volumes:
      - transaction_db_data:/var/lib/postgresql

  config-server:
    image: config-server:latest
    container_name: config-server
    ports:
      - "8888:8888"

  eureka-server:
    image: eureka-server:latest
    container_name: eureka-server
    depends_on:
      - config-server
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
    ports:
      - "8761:8761"

  account-service:
    image: account-service:latest
    container_name: account-service
    depends_on:
      - account-db
      - config-server
      - eureka-server
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
    ports:
      - "8081:8081"

  transaction-service:
    image: transaction-service:latest
    container_name: transaction-service
    depends_on:
      - transaction-db
      - account-service
      - config-server
      - eureka-server
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
    ports:
      - "8082:8082"

  api-gateway:
    image: api-gateway:latest
    container_name: api-gateway
    depends_on:
      - config-server
      - eureka-server
      - account-service
      - transaction-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
    ports:
      - "8080:8080"

volumes:
  account_db_data:
  transaction_db_data: