services:
  account-db:
    image: postgres:18
    container_name: account-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: AccountService
    ports:
      - "5433:5432"
    volumes:
      - account_db_data:/var/lib/postgresql

  transaction-db:
    image: postgres:18
    container_name: transaction-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: TransactionService
    ports:
      - "5434:5432"
    volumes:
      - transaction_db_data:/var/lib/postgresql

  account-service:
    image: account-service:latest
    container_name: account-service
    depends_on:
      - account-db
    ports:
      - "8081:8081"

  transaction-service:
    image: transaction-service:latest
    container_name: transaction-service
    depends_on:
      - transaction-db
      - account-service
    ports:
      - "8082:8082"

volumes:
  account_db_data:
  transaction_db_data: