spring:
  application:
    name: account-service

  datasource:
    url: jdbc:postgresql://localhost:5433/AccountService  #for local machine
    #for docker
#    url: jdbc:postgresql://account-db:5432/AccountService
    username: root
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
    show-sql: true

  sql:
    init:
      mode: always
      data-locations: classpath:account-service-data.sql


server:
  port: 8081

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace

jwt:
  secret: "8f2a91c6e4b7d3f0a5c8e1b4d7f0a3c6e9b2d5f8a1c4e7b0d3f6a9c2e5b8d1f4"